### ISSUE TITLE
Typo: "Depends: nmap, ngingx"

### ISSUE THREAD

**Issue by jgamblin** [KruDex/lan-monitor#5]
lan-monitor/pkg-build/lan-monitor/DEBIAN/control

Package: lan-monitor
Architecture: all
Maintainer: thomas.krueger.home@gmail.com
Priority: optional
Version: 1.2.0
Depends: nmap, ngingx
Description: Automatically generated website to list computers
    The computer list is based on a nmap scan of the assigned network with ports listed

This is breaking the install.

**Comment by jgamblin** [comment]
The install is also not copying the files where they should end up. 

admin@ip-172-26-15-29:~/lan-monitor/pkg-build$ sudo ./build-deb-pkg.sh 
cp: cannot stat ‘../bin/lan-monitor-scan.sh’: No such file or directory
dpkg-deb: building package `lan-monitor' in `lan-monitor.deb'.

This looks like an amazingly cool project and I am looking forward to seeing it work.

**Comment by KruDex** [comment]
Thanks for the feedback, I will fix it

**Comment by KruDex** [comment]
Dear Jerry,

thanks for hinting this out. It is fixed now in release version v.1.4.0. The Debian package can be directly downloaded (here)[https://github.com/KruDex/lan-monitor/releases/download/v1.4.0/lan-monitor.deb].

 But please not that it will overwrite/delete the *nginx/sites-enabled/default* and in addition the scan range still needs to be set manually after installing in */usr/bin/lan-monitor-scan.sh* according to the README notes. I will think of how to improve.

Every additional feedback is very welcome :-)

**Comment by jgamblin** [comment]
Thank you!  It is working now but I am looking at this for a much for public use (scan public range continually with nmap).


Here are a couple of suggestions:

- Only show Hosts with open ports. 
- Extend the scan to NMAPs Top 10, 100 or 1000 ports as options. 
https://danielmiessler.com/blog/nmap-use-the-top-ports-option-for-both-tcp-and-udp-simultaneously/#gs.yxvP2N0
- Have the name show the full DNS name if possible. 

All and all this is pretty amazing! 

Thanks,

Jerry

**Comment by KruDex** [comment]
Thanks a lot, I never saw the possibility to use it as public scan and the top-ports sounds very interesting... Just be careful, aws almost kicked me out because I scanned once my own home from my cloud machine with nmap - maybe even certain internet providers might have this in terms and conditions...

To make the output more configurable (show certain host and/or ports only, dns-names etc. will be my next step)
